playstation/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from sale.views import *
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', homepage_view,name = 'home'),
    path('sale/', include('sale.urls'))
    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sale/urls.py
from django.conf.urls import url
from django.urls import path,re_path
from .views import *

app_name = 'sale'

urlpatterns = [
    path('plus-sale',plus_view,name='plus'),
    # path('plus-detail<int:id/>', detail_view,name='detail'),
    path('rent', rent_view,name='rent'),
    path('game', game_view,name='game'),
    path('psn-sale', psn_view,name='psn'),
    url(r'^(?P<id>[\w-]+)/plus-detail/$', detail_view, name="detail"),
    url(r'^(?P<id>[\w-]+)/game-detail/$', game_detail, name="gamedetail"),
    url(r'^(?P<id>[\w-]+)/psn-detail/$', psn_detail_view, name="psn-detail"),

]

sale/models.py
from django.db import models
from django.urls import reverse


class Region(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


choices = ('1', '1'), ('3', '3'), ('12', '12')


class Plus(models.Model):
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    image = models.ImageField()
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    period = models.CharField(max_length=255, choices=choices)

    def __str__(self):
        return str(self.name) + str(self.price) + 'manat'

    def get_absolute_url(self):
        return reverse("sale:detail", kwargs={"id": self.id})

    class Meta:
        verbose_name_plural = "plus"


class PSN(models.Model):
    name = models.CharField(max_length=255)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    image = models.ImageField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def get_absolute_url(self):
        return reverse("sale:psn-detail", kwargs={"id": self.id})


    class Meta:
        verbose_name_plural = 'PSN'


class Game(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("sale:gamedetail", kwargs={'id':self.id})

sale/views.py
from django.shortcuts import render
from .models import Plus,PSN,Game
from django.db.models import Q

# Create your views here.


def homepage_view(request):
    return render(request, 'home.html')


def plus_view(request):
    plus = Plus.objects.all()
    return render(request, 'sale/plus.html', {'plus': plus})


def detail_view(request, id):
    plus = Plus.objects.get(id=id)
    return render(request, "sale/detailplus.html", {'plus': plus})

def psn_detail_view(request, id):
    plus = PSN.objects.get(id=id)
    return render(request, "sale/detailpsn.html", {'psn': plus})

def psn_view(request):
    psn = PSN.objects.all()
    return render(request,"sale/psn.html",{'psn':psn})


def rent_view(request):
    return render(request, 'icare.html')

def game_view(request):
    game = Game.objects.all()
    query = request.GET.get('q')
    if query:
        game = game.filter(
            Q(name__icontains=query)
        ).distinct()
    return render(request,'sale/game.html',{'plus':game})

def game_detail(request,id):
    game = Game.objects.get(id=id)
    return render(request,'sale/gamedetail.html',{'psn':game})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Tech Baku</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/tblogo.png' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
</head>
<body>
{% include "header.html" %}
{% block body %}


{% endblock  %}
{% include 'footer.html' %}
<style>
body {
  background-image: url('https://images3.alphacoders.com/102/1020596.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed; 
  background-size: cover;
}
* {
    font-family: 'Roboto', sans-serif;
}
</style>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/footer.html
  <footer id="sticky-footer" class="py-4 bg-dark text-white-50 bottom">
    <div class="container text-center">
      <small>Copyright &copy; techbaku.com</small><br>
      <small><a href="https://www.instagram.com/edelgamecenter/">İnstagram hesabımız</a></small><br>
      {% comment %} <small>Əlaqə : +994508971240</small><br> {% endcomment %}
    </div>
  </footer>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #285F99;">
  <a class="navbar-brand" href="{% url 'home' %}" style='color:white'>TechBaku</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sale:plus' %}">Playtation Plus+</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Digər
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'sale:rent' %}">Playtation4 icarə</a>
          <a class="dropdown-item" href="{% url 'sale:psn' %}">Playtation Gift card</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'sale:game' %}">Oyunlar</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action='{% url "sale:game" %}'>
      <input class="form-control mr-sm-2" name='q' type="search" placeholder="Oyunun adı..." aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Axtar</button>
    </form>
  </div>
</nav>

templates/home.html
{% extends "base.html" %}

{% load static %}

{% block body %}
<br><br><br>
<div class='container'>
  <div class="row" style="padding-top:10px">
    <a href="{% url 'sale:rent'  %}">
      <div class="col mb-3" style="max-height:50px">
        <div class="card">
          <img src="{% static 'img/homeps.jpeg' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Playstation4 İcarə</h5>
            <p class="card-text"></p>
          </div>
        </div>
    </a>
  </div>
  <a href="{% url 'sale:plus'  %}">
    <div class="col mb-3">
      <div class="card">
        <img src="{% static 'img/psn.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Playstation Plus+</h5>
        </div>
      </div>
  </a>
</div>
<a href="{% url 'sale:psn' %}">
  <div class="col mb-3">
    <div class="card">
      <img src="{% static 'img/psnow.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Playstation Gift Cards</h5>
      </div>
    </div>

</a>
</div>
<a href="{% url 'sale:game' %}">
<div class="col mb-3">
  <div class="card">
    <img src="{% static 'img/game.jpg' %}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Oyunlar</h5>
    </div>
  </div>
</a>
</div>
</div>
</div>
<br><br><br><br><br>
{% endblock  %}

templates/icare.html
{% extends "base.html" %}
{% comment %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> {% endcomment %}
<!------ Include the above in your HEAD tag ---------->
{% load static %}
{% block body %}


<div class="container">
    <hr>


    <div class="card rounded shadow-lg p-3 mb-5 bg-white" style='text-align:center'>
        <div class="row">
            <aside class="col-sm-5 border-right">
                <article class="gallery-wrap">
                    <div class="img-big-wrap">
                        <div><a href="https://www.instagram.com/edelgamecenter/"><img src="{% static 'img/homeps474.jpg' %}" class="card-img-top"></a></div>
                    </div> <!-- slider-product.// -->
                    <div class="img-small-wrap">

                    </div> <!-- slider-nav.// -->
                </article> <!-- gallery-wrap .end// -->
            </aside>
            <aside class="col-sm-7">
                <article class="card-body p-5">
                    <h3 class="title mb-3">Playstation4 Slim 1TB</h3>

                    <p class="price-detail-wrap">
                        <span class="price h3 text-warning">
                            <span class="currency" style="color:black">Qiymət :</span>
                        </span>
                    </p> <!-- price-detail-wrap .// -->
                    <dl class="item-property">
                            <dd>

                                    • Günlük icarə : 18 AZN<br>
                                    • 3 Günlük icarə : 45 AZN<br>
                                    • Həftəlik icarə : 100 AZN<br>
                            </dd>
                        </dl>
                        <dt>Məlumat</dt>
                        <dd>
                            <p>Model:Playstation 4 slim 1tb(black)
                                <br>

                                Aksesuarlar: 2 ədəd Dualshock 4
                                <br>
                                Game List:<br>
                                • Fifa 20<br>
                                • Pes20<br>
                                • Gta 5<br>
                                • UFC 3<br>
                                • Mortal kombat 11<br>
                                • Call of Duty Black ops 2<br>
                                • God of War<br>
                                • Days Gone<br>
                                • Spiderman<br>
                                • The last of us<br>
                                • Uncharted 4<br>
                                • Need for speed<br>
                                • Rocket League<br>
                                • Drive Club<br>
                                • Horizon zero down<br>
                                • Crash Bandicot<br>
                                • Crash Racing Nitro<br>
                                • Bloodborne</p><br>
                        </dd>
                    </dl>
                    <a href="https://www.instagram.com/edelgamecenter/"><img src="{% static 'img/instagram.png' %}" style="width:90px"></a>

        </div> <!-- row.// -->
        <hr>

    </div> <!-- row.// -->
</div> <!-- card.// -->


</div>
<!--container.//-->



{% endblock %}

templates/sale/detailplus.html
{% extends "base.html" %}
{% comment %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> {% endcomment %}
<!------ Include the above in your HEAD tag ---------->
{% load static %}
{% block body %}


<div class="container">
    <hr>


    <div class="card" style='text-align:center'>
        <div class="row">
            <aside class="col-sm-5 border-right">
                <article class="gallery-wrap">
                    <div class="img-big-wrap">
                        <div> <a href="#"><img class='rounded shadow-lg p-3 mb-5 bg-white rounded' src="{{plus.image.url}}"></a></div>
                    </div> <!-- slider-product.// -->
                    <div class="img-small-wrap">

                    </div> <!-- slider-nav.// -->
                </article> <!-- gallery-wrap .end// -->
            </aside>
            <aside class="col-sm-7">
                <article class="card-body p-5">
                    <h3 class="title mb-3">{{plus.name}} {{plus.region}} regionu {{plus.period}} Aylıq  </h3>

                    <p class="price-detail-wrap">
                        <span class="price h3 text-warning">
                            <span class="currency">{{plus.price}} AZN</span>
                        </span>
                    </p> <!-- price-detail-wrap .// -->
                    <dl class="item-property">
                        <dt>Məlumat</dt>
                        <dd>
                            <p>
                                • Aylıq Plus+ üçün 3 pulsuz oyun<br>
                                • Playstation Store'da Xüsusi Endirimlər <br>
                                • Oyunlarınızı online oynamaq imkanı <br>
                            </p>
                        </dd>
                    </dl>
                    <dl class="param param-feature">
                        <dt>Region :</dt>
                        <dd>{{plus.region}}</dd>
                    </dl> <!-- item-property-hor .// -->
                    <dl class="param param-feature">
                        <dt>Qiymət :</dt>
                        <dd>{{plus.price}} AZN</dd>
                    </dl> <!-- item-property-hor .// -->
                    <dl class="param param-feature">
                        <dt>Sifariş</dt>
                        <dd>Məhsulu sifariş etmək üçün zəhmət olmasa <a href="https://www.instagram.com/edelgamecenter/"> instagram hesabımız</a>a yazın</dd>
                    </dl> <!-- item-property-hor .// -->
                    <a href="https://www.instagram.com/edelgamecenter/"><img src="{% static 'img/instagram.png' %}" style="width:90px"></a>
        </div> <!-- row.// -->
        <hr>
        
        </article> <!-- card-body.// -->
        </aside> <!-- col.// -->
    </div> <!-- row.// -->
</div> <!-- card.// -->


</div>
<!--container.//-->


</article>
{% endblock %}

templates/sale/detailpsn.html
{% extends "base.html" %}
{% comment %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> {% endcomment %}
<!------ Include the above in your HEAD tag ---------->
{% load static %}
{% block body %}


<div class="container">
    <hr>


    <div class="card" style='text-align:center'>
        <div class="row">
            <aside class="col-sm-5 border-right">
                <article class="gallery-wrap">
                    <div class="img-big-wrap">
                        <div> <a href="#"><img class="rounded shadow-lg p-3 mb-5 bg-white img-fluid" alt="Responsive image" src="{{psn.image.url}}"></a></div>
                    </div> <!-- slider-product.// -->
                    <div class="img-small-wrap">

                    </div> <!-- slider-nav.// -->
                </article> <!-- gallery-wrap .end// -->
            </aside>
            <aside class="col-sm-7">
                <article class="card-body p-5">
                    <h3 class="title mb-3">{{psn.name}} {{psn.region}} regionu</h3>

                    <p class="price-detail-wrap">
                        <span class="price h3 text-warning">
                            <span class="currency">{{psn.price}} AZN</span>
                        </span>
                    </p> <!-- price-detail-wrap .// -->
                    <dl class="item-property">
                        <dt>Məlumat</dt>
                        <dd>
                            <p >
                                • Playstation Store'da  Azərbaycan Kartlarının işləmədiyi üçün Playstation Gift Kartlarla 
                                xidmətinizdəyik. <br>
                                • İstənilən Region üçün istənilən Qiymətə Seçib ala Bilərsiniz<br>
                            </p>
                        </dd>
                    </dl>
                    <dl class="param param-feature">
                        <dt>Region :</dt>
                        <dd>{{psn.region}}</dd>
                    </dl> <!-- item-property-hor .// -->
                    <dl class="param param-feature">
                        <dt>Qiymət :</dt>
                        <dd>{{psn.price}} AZN</dd>
                    </dl> <!-- item-property-hor .// -->
                    <dl class="param param-feature">
                        <dt>Sifariş</dt>
                        <dd>Məhsulu sifariş etmək üçün zəhmət olmasa <a href="https://www.instagram.com/edelgamecenter/"> instagram hesabımız</a>a yazın</dd>
                    </dl> <!-- item-property-hor .// -->
                    <a href="https://www.instagram.com/edelgamecenter/"><img src="{% static 'img/instagram.png' %}" style="width:90px"></a>
        </div> <!-- row.// -->
        <hr>
        
        </article> <!-- card-body.// -->
        </aside> <!-- col.// -->
    </div> <!-- row.// -->
</div> <!-- card.// -->


</div>
<!--container.//-->



{% endblock %}

templates/sale/game.html
{% extends "base.html" %}

{% block body %}
<hr>
<div class="container">
    <div class="row">
        {% for plus in plus %}

        <a href="{{plus.get_absolute_url}}">
        <div class="col- col-md col-sm-6 col-lg" style="padding-bottom:20px">
            <div class="card" style="width:12rem;display: inline-block;">
                <img src="{{plus.image.url}}" class="img-fluid">
                <div class="card-body">
                    <h5 class="card-title">{{plus.name}}</h5>
                    <p class="card-text">{{plus.price}} AZN</p>
                </div>
            </div>
        </div>
        </a>

        {% endfor %}
    </div>
</div>
<br><br><br><br><br>
<hr>
{% endblock %}

templates/sale/gamedetail.html
{% extends "base.html" %}
{% comment %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> {% endcomment %}
<!------ Include the above in your HEAD tag ---------->
{% load static %}
{% block body %}


<div class="container">
    <hr>


    <div class="card" style='text-align:center'>
        <div class="row">
            <aside class="col-sm-5 border-right">
                <article class="gallery-wrap">
                    <div class="img-big-wrap">
                        <div> <a href="#"><img class="rounded shadow-lg p-3 mb-5 bg-white img-fluid" alt="Responsive image" src="{{psn.image.url}}"></a></div>
                    </div> <!-- slider-product.// -->
                    <div class="img-small-wrap">

                    </div> <!-- slider-nav.// -->
                </article> <!-- gallery-wrap .end// -->
            </aside>
            <aside class="col-sm-7">
                <article class="card-body p-5">
                    <h3 class="title mb-3">{{psn.name}} {{psn.region}}</h3>

                    <p class="price-detail-wrap">
                        <span class="price h3 text-warning">
                            <span class="currency">{{psn.price}} AZN</span>
                        </span>
                    </p> <!-- price-detail-wrap .// -->
                    <dl class="item-property">
                        <dt>Məlumat</dt>
                        <dd>
                            <p >
                                {{psn.name}} Oyunu Ən Münasib Qiymətə artıq satışda !
                            </p>
                        </dd>
                    </dl>
                    <dl class="param param-feature">
                        <dt>Qiymət :</dt>
                        <dd>{{psn.price}} AZN</dd>
                    </dl> <!-- item-property-hor .// -->
                    <dl class="param param-feature">
                        <dt>Sifariş</dt>
                        <dd>Məhsulu sifariş etmək üçün zəhmət olmasa <a href="https://www.instagram.com/edelgamecenter/"> instagram hesabımız</a>a yazın</dd>
                    </dl> <!-- item-property-hor .// -->
                    <a href="https://www.instagram.com/edelgamecenter/"><img src="{% static 'img/instagram.png' %}" style="width:90px"></a>
        </div> <!-- row.// -->
        <hr>
        
        </article> <!-- card-body.// -->
        </aside> <!-- col.// -->
    </div> <!-- row.// -->
</div> <!-- card.// -->


</div>
<!--container.//-->



{% endblock %}

templates/sale/plus.html
{% extends "base.html" %}

{% block body %}
<hr>
<div class="container">
    <div class="row">
        {% for plus in plus %}
        <a href="{{plus.get_absolute_url}}">
        <div class="col-md-3" style="padding-bottom:20px">
            <div class="card" style="width: 12rem;display: inline-block;">
                <img src="{{plus.image.url}}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{plus.title}}</h5>
                    <p class="card-text">{{plus.price}} AZN (3 ayliq)</p>
                </div>
            </div>
        </div>
        </a>

        {% endfor %}
    </div>
</div>
{% endblock %}

templates/sale/psn.html
{% extends "base.html" %}

{% block body %}
<hr>
<div class="container">
    <div class="row">
        {% for psn in psn %}

        <a href="{{psn.get_absolute_url}}">
        <div class="col col-md-3" style="padding-bottom:20px">
            <div class="card" style="width: 12rem;display: inline-block;">
                <img src="{{psn.image.url}}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{psn.name}}</h5>
                    <p class="card-text">{{psn.price}} AZN</p>
                </div>
            </div>
        </div>
        </a>

        {% endfor %}
    </div>
</div>
{% endblock %}